# Generated by Django 6.0.4 on 2026-04-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessClass',
            fields=[
                ('classid', models.AutoField(db_column='classid', primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=100)),
                ('day_of_week', models.CharField(blank=True, max_length=20, null=True)),
                ('class_time', models.CharField(blank=True, max_length=20, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructorid', models.AutoField(db_column='instructorid', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('specialty', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'instructor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('memberid', models.AutoField(db_column='memberid', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('planid', models.AutoField(db_column='planid', primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=100, unique=True)),
                ('price_per_month', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('classes_per_month', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'membership_plan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('registrationid', models.AutoField(db_column='registrationid', primary_key=True, serialize=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'registration',
                'managed': False,
            },
        ),
    ]
